//! Built-in color profiles for the terminal emulator.
//!
//! These are seeded into the `color_profiles` table on the v2 migration and
//! marked `is_builtin = 1` so the user can't accidentally delete them.

/// Static definition of a color profile — used only for seeding.
pub struct BuiltinProfile {
    pub id: &'static str,
    pub name: &'static str,
    pub foreground: &'static str,
    pub background: &'static str,
    pub cursor: &'static str,
    pub selection: &'static str,
    pub black: &'static str,
    pub red: &'static str,
    pub green: &'static str,
    pub yellow: &'static str,
    pub blue: &'static str,
    pub magenta: &'static str,
    pub cyan: &'static str,
    pub white: &'static str,
    pub bright_black: &'static str,
    pub bright_red: &'static str,
    pub bright_green: &'static str,
    pub bright_yellow: &'static str,
    pub bright_blue: &'static str,
    pub bright_magenta: &'static str,
    pub bright_cyan: &'static str,
    pub bright_white: &'static str,
}

pub const BUILTIN_PROFILES: &[BuiltinProfile] = &[
    // Tokyo Night — the default
    BuiltinProfile {
        id: "tokyo-night",
        name: "Tokyo Night",
        foreground: "#c0caf5",
        background: "#1a1b26",
        cursor: "#c0caf5",
        selection: "#33467c",
        black: "#15161e",
        red: "#f7768e",
        green: "#9ece6a",
        yellow: "#e0af68",
        blue: "#7aa2f7",
        magenta: "#bb9af7",
        cyan: "#7dcfff",
        white: "#a9b1d6",
        bright_black: "#414868",
        bright_red: "#f7768e",
        bright_green: "#9ece6a",
        bright_yellow: "#e0af68",
        bright_blue: "#7aa2f7",
        bright_magenta: "#bb9af7",
        bright_cyan: "#7dcfff",
        bright_white: "#c0caf5",
    },
    // One Half Dark
    BuiltinProfile {
        id: "one-half-dark",
        name: "One Half Dark",
        foreground: "#dcdfe4",
        background: "#282c34",
        cursor: "#dcdfe4",
        selection: "#3e4452",
        black: "#282c34",
        red: "#e06c75",
        green: "#98c379",
        yellow: "#e5c07b",
        blue: "#61afef",
        magenta: "#c678dd",
        cyan: "#56b6c2",
        white: "#dcdfe4",
        bright_black: "#5c6370",
        bright_red: "#e06c75",
        bright_green: "#98c379",
        bright_yellow: "#e5c07b",
        bright_blue: "#61afef",
        bright_magenta: "#c678dd",
        bright_cyan: "#56b6c2",
        bright_white: "#dcdfe4",
    },
    // Campbell (Windows Terminal default)
    BuiltinProfile {
        id: "campbell",
        name: "Campbell",
        foreground: "#cccccc",
        background: "#0c0c0c",
        cursor: "#ffffff",
        selection: "#264f78",
        black: "#0c0c0c",
        red: "#c50f1f",
        green: "#13a10e",
        yellow: "#c19c00",
        blue: "#0037da",
        magenta: "#881798",
        cyan: "#3a96dd",
        white: "#cccccc",
        bright_black: "#767676",
        bright_red: "#e74856",
        bright_green: "#16c60c",
        bright_yellow: "#f9f1a5",
        bright_blue: "#3b78ff",
        bright_magenta: "#b4009e",
        bright_cyan: "#61d6d6",
        bright_white: "#f2f2f2",
    },
    // Solarized Dark
    BuiltinProfile {
        id: "solarized-dark",
        name: "Solarized Dark",
        foreground: "#839496",
        background: "#002b36",
        cursor: "#839496",
        selection: "#073642",
        black: "#073642",
        red: "#dc322f",
        green: "#859900",
        yellow: "#b58900",
        blue: "#268bd2",
        magenta: "#d33682",
        cyan: "#2aa198",
        white: "#eee8d5",
        bright_black: "#002b36",
        bright_red: "#cb4b16",
        bright_green: "#586e75",
        bright_yellow: "#657b83",
        bright_blue: "#839496",
        bright_magenta: "#6c71c4",
        bright_cyan: "#93a1a1",
        bright_white: "#fdf6e3",
    },
    // Solarized Light
    BuiltinProfile {
        id: "solarized-light",
        name: "Solarized Light",
        foreground: "#657b83",
        background: "#fdf6e3",
        cursor: "#657b83",
        selection: "#eee8d5",
        black: "#073642",
        red: "#dc322f",
        green: "#859900",
        yellow: "#b58900",
        blue: "#268bd2",
        magenta: "#d33682",
        cyan: "#2aa198",
        white: "#eee8d5",
        bright_black: "#002b36",
        bright_red: "#cb4b16",
        bright_green: "#586e75",
        bright_yellow: "#657b83",
        bright_blue: "#839496",
        bright_magenta: "#6c71c4",
        bright_cyan: "#93a1a1",
        bright_white: "#fdf6e3",
    },
    // Tango Dark
    BuiltinProfile {
        id: "tango-dark",
        name: "Tango Dark",
        foreground: "#d3d7cf",
        background: "#2e3436",
        cursor: "#d3d7cf",
        selection: "#4e585d",
        black: "#2e3436",
        red: "#cc0000",
        green: "#4e9a06",
        yellow: "#c4a000",
        blue: "#3465a4",
        magenta: "#75507b",
        cyan: "#06989a",
        white: "#d3d7cf",
        bright_black: "#555753",
        bright_red: "#ef2929",
        bright_green: "#8ae234",
        bright_yellow: "#fce94f",
        bright_blue: "#729fcf",
        bright_magenta: "#ad7fa8",
        bright_cyan: "#34e2e2",
        bright_white: "#eeeeec",
    },
    // Dracula
    BuiltinProfile {
        id: "dracula",
        name: "Dracula",
        foreground: "#f8f8f2",
        background: "#282a36",
        cursor: "#f8f8f2",
        selection: "#44475a",
        black: "#21222c",
        red: "#ff5555",
        green: "#50fa7b",
        yellow: "#f1fa8c",
        blue: "#bd93f9",
        magenta: "#ff79c6",
        cyan: "#8be9fd",
        white: "#f8f8f2",
        bright_black: "#6272a4",
        bright_red: "#ff6e6e",
        bright_green: "#69ff94",
        bright_yellow: "#ffffa5",
        bright_blue: "#d6acff",
        bright_magenta: "#ff92df",
        bright_cyan: "#a4ffff",
        bright_white: "#ffffff",
    },
];
